// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task.API_Context;

#nullable disable

namespace Test_Task.Migrations
{
    [DbContext(typeof(Db_Context))]
    partial class Db_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Test_Task.Models.Candidate", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GitHub_profile_URL")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("varchar(300)");

                    b.Property<string>("LinkedIn_profile_URL")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Phone_number")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Time_interval_call")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Email");

                    b.ToTable("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
